# .pre-commit-config.yaml
minimum_pre_commit_version: "3.0.0"

repos:
  # ───────────────────────────── Terraform workflow ────────────────────────────
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.0            # ← pinned release (2025-05-xx)
    hooks:
      - id: terraform_fmt
        args: ["-recursive"]          # formats *.tf and *.tfvars
      - id: terraform_validate
      - id: terraform_tflint          # respects .tflint.hcl in repo root
        args: ["--config=./.tflint.hcl", "--recursive"]
      - id: terraform_docs            # auto-updates module README
        args:
          [
            "--output-file", "README.md",
            "--output-mode", "inject",
            "--config", ".terraform-docs.yml",
            "--quiet"
          ]
      - id: terraform_tfsec           # https://tfsec.dev
        args: ["--config-file=.tfsec.yaml", "--soft-fail=false"]

  # ───────────────────────────── Security / secrets ────────────────────────────
  # - repo: https://github.com/zricethezav/gitleaks
  #   rev: v8.18.0
  #   hooks:
  #     - id: gitleaks
  #       args: ["--verbose", "--config=.gitleaks.toml"]

  # - repo: https://github.com/bridgecrewio/checkov
  #   rev: 3.2.435
  #   hooks:
  #     - id: checkov
  #       args: ["--quiet", "--compact-report", "--framework", "terraform"]

  # ───────────────────────────── General hygiene ───────────────────────────────
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-merge-conflict

  # ───────────────────────────── YAML / JSON / Shell ───────────────────────────
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
        files: ^.*\.py$

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        files: ^.*\.sh$

  # ───────────────────────────── Commit-message policy ─────────────────────────
  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v4.8.2
  #   hooks:
  #     - id: commitizen
  #       stages: [commit-msg]
  #       args: ["--retry"]
